### ISSUE TITLE
An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by manuel-uberti** [clojure-emacs/orchard#43] opened 2019-02-14 09:34 UTC
## Expected behavior

`shadow-cljs watch my-project` runs without warnings.

## Actual behavior

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by mranderson048.orchard.v0v3v0.dynapath.v0v2v5.dynapath.defaults$eval8306$fn__8307 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of mranderson048.orchard.v0v3v0.dynapath.v0v2v5.dynapath.defaults$eval8306$fn__8307
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

## Steps to reproduce the problem

The easiest way to reproduce the bug is:

- install [shadow-cljs](http://shadow-cljs.org/)
- clone my repository [here](https://github.com/manuel-uberti/boodle)
- run `shadow-cljs watch boodle`

### Clojure version

1.10.0

### Java version

```
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-3ubuntu118.04ppa1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-3ubuntu118.04ppa1, mixed mode, sharing)
```

### Operating system

Ubuntu 18.04

## Note

I reported this here because I saw `orchard` in the messages. Feel free to close the issue (and/or tell me where to open it instead) if I'm in the wrong place.

**Comment by bbatsov** [comment] 2019-03-20 06:09
That's a duplicate of #20.

**Closed by bbatsov** 2019-03-20 06:09 UTC
