### ISSUE TITLE
Figure out what to do with our dynapath 1.0 compatibility problems

### ISSUE THREAD

**Issue by bbatsov** [clojure-emacs/orchard#20] opened 2018-02-23 03:54 UTC
Long story short:

* We don't support the latest version of dynapath (1.0)
* The version we're using (0.2.5) is going to stop working with Java 10, as it relied on implementation details that are going to be changed

We need to come up with some solution for this soon, otherwise it's going to cause problems for many people. 

More details here https://github.com/clojure-emacs/cider-nrepl/issues/482

**Comment by tsulej** [comment] 2018-03-29 22:15
Maybe it's related, I've just checked Java 10 and got such warning. nRepl and Cider seem to work.

nREPL server started on port 51299 on host 127.0.0.1 - nrepl://127.0.0.1:51299
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by mranderson048.orchard.v0v1v0_20180321v113210_28.dynapath.v0v2v5.dynapath.defaults$eval7485$fn__7486 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of mranderson048.orchard.v0v1v0_20180321v113210_28.dynapath.v0v2v5.dynapath.defaults$eval7485$fn__7486
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
REPL-y 0.3.7, nREPL 0.2.12
Clojure 1.9.0
Java HotSpot(TM) 64-Bit Server VM 10+46

**Comment by SevereOverfl0w** [comment] 2018-03-30 13:51
Mirroring the boot approach seems difficult unless we control the start of the JVM very closely. I believe it needs to run prior to clojure.

**Comment by bbatsov** [comment] 2018-03-31 03:40
Unfortunately I'm out of other ideas. I'm guessing something must be possible, but I simply don't have the time to do the research for it. The fact that dynapath decided to drop this functionality instead of fixing it leads me to believe probably there's no easy solution, though.

**Comment by SevereOverfl0w** [comment] 2018-04-01 14:06
Inside of boot, I think we're okay, as we can use their compatible classloader.

What features does dynapath provide to us?

**Comment by bbatsov** [comment] 2018-04-01 19:19
We use it only to add the JDK resources dynamically to the classpath, so afterwards things like source lookup and doc lookup will work for them. See https://github.com/clojure-emacs/orchard/blob/3934ea63117b3cd3f1b459e66ada05ac173a1fc1/src/orchard/java.clj#L32

Unfortunately we're using exactly the damn method that the deprecation warnings are about. :-)

**Comment by tirkarthi** [comment] 2018-04-02 06:18
>     A re-implementation of add-classpath (deprecated in Clojure core) that:
>     is a little more comprehensive than core's add-classpath — it should work as expected in more circumstances, and optionally uses Maven-resolver to add a Maven artifact (and all of its transitive dependencies) to your Clojure runtime's classpath dynamically.

I don't know how viable it is to use pomegranate but quick googling led me to this from a [comment](https://clojuredocs.org/clojure.core/add-classpath#example-59d7d6d8e4b03026fe14ea57) on clojuredocs

**Comment by SevereOverfl0w** [comment] 2018-04-02 08:11
Pomegranate uses dynapath, https://github.com/cemerick/pomegranate/blob/master/README.md#urlclassloader-modifiability

On April 2, 2018 7:18:34 AM GMT+01:00, Xtreak <notifications@github.com> wrote:
>>     A re-implementation of add-classpath (deprecated in Clojure core)
>that:
>>     is a little more comprehensive than core's add-classpath — it
>should work as expected in more circumstances, and optionally uses
>Maven-resolver to add a Maven artifact (and all of its transitive
>dependencies) to your Clojure runtime's classpath dynamically.
>
>I don't know how viable it is to use pomegranate but quick googling led
>me to this from a
>[comment](https://clojuredocs.org/clojure.core/add-classpath#example-59d7d6d8e4b03026fe14ea57)
>on clojuredocs
>
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/clojure-emacs/orchard/issues/20#issuecomment-377864477

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bbatsov** [comment] 2018-04-12 06:09
@SevereOverfl0w Not sure they have a real workaround. 

> If you are in a situation where you are using pomegranate but do not have a clojure.lang.DynamicClassLoader visible in your classloader hierarchy, you will need to explicitly enable the java.net.URLClassLoader support in dynapath (upon which pomegranate relies for such things).

This sounds like some flag to suppress the new behavior or something. And I don't see it in dynapath's readme.

**Comment by SevereOverfl0w** [comment] 2018-04-12 08:40
Why are we not under clojure.lang.DynamicClassLoader when running?

**Comment by bbatsov** [comment] 2018-04-13 14:35
No idea to be honest. I think @jeffvalk worked on this originally and we never had to change the code afterwards. Maybe he remembers something about this.

**Comment by jeffvalk** [comment] 2018-04-13 21:59
For full Java source support, we need the JDK compiler classes in `tools.jar`, which is not on the classpath by default. It's also nice to have `src.zip`, so that the JDK class sources are available to the `info` middleware (jump-to, class/member docstrings, etc). 

Dynapath was (at the time anyway...) the best option for loading these at runtime. And I believe dynapath does use a `clojure.lang.DynamicClassLoader` internally.

The use of dynapath wasn't very sophisticated; we just need to append those two resources to the classpath.

**Comment by zcaudate** [comment] 2018-07-06 01:50
I'm personally fine with the reflective warnings. are you sure java 10 is going to ban it completely?

if cider can modify the ns macro https://github.com/clojure/clojure/blob/010864f8ed828f8d261807b7345f1a539c5b20df/src/clj/clojure/core.clj#L5553

to provide a alternate classloader with the additional urls, then it might work.

**Comment by zcaudate** [comment] 2018-07-06 02:02
Actually. I realised it's a slightly different problem (I was thinking in-editor evaluation), because `ns` doesn't have to be evalutated, it's a little easier to go around the dynapath thing. 

Just write an alternate `load` method. 

https://github.com/clojure/clojure/blob/010864f8ed828f8d261807b7345f1a539c5b20df/src/clj/clojure/core.clj#L5876-L5893

**Comment by jmingtan** [comment] 2018-11-28 16:06
Hi, I'd like to summarize my understanding on this issue, and get some feedback from the maintainers if possible, especially to clear up any misconceptions :)

This is what I understand from reading the code, and from @jeffvalk's comments:

1. The sole namespace in orchard that depends on dynapath is `orchard.java`, which uses it to dynamically add the JDK's src.zip and tools.jar to the classpath
2. tools.jar is needed solely for access to the Javadoc classes, by `orchard.java.parser` whose job is to return source information (line numbers, docstrings) from a Java source file
3. src.zip is needed solely for source code lookup on JDK classes

Here are some minor problems posed by JDK version 9 and above:

- tools.jar is now removed, because the jdk classes are now present on the classpath
- java.home now returns the path to the jdk folder instead of the jre folder
- src.zip is moved into ${java.home}/lib

Here are the more major problems with JDK 9 and above:

- we're not able to "hack" `java.net.URLClassLoader` to invoke its protected methods anymore, making it harder to dynamically add new classpaths in the default class loader chain
- internally, src.zip has undergone a restructuring where each package is now under its corresponding module folder (e.g. "java.base/java/lang/String.java") which breaks the current lookup mechanism
- IMO the biggest problem is the Javadoc classes that parser.clj depends on can't be called because they are not being exported by the jdk.javadoc module. Trying to call their methods results in an IllegalAccessError.

I'm actually hoping I'm wrong on that last point, otherwise I think it means we need to rewrite parser.clj just to support JDK 9 and above - there's a project called [javaparser](http://javaparser.org) that might help, but it would mean bringing in a new dependency. I guess my question is does this sound like a good approach? is there a strong preference not to bring in new dependencies?

The short-term approach here might just be to detect if JDK >= 9 and just not call `add-classpath!` in order to prevent any illegal access warnings. This would prevent source-info lookup, but I think that would be broken anyway due to not having access to jdk classes.

**Comment by jeffvalk** [comment] 2018-11-28 18:43
Great summary, @jmingtan. This all sounds right to me at first read.

Regarding the big problem:
> the biggest problem is the Javadoc classes that parser.clj depends on can't be called because they are not being exported by the jdk.javadoc module. Trying to call their methods results in an IllegalAccessError.

The `com.sun.javadoc` classes are now at [jdk.javadoc.doclet][1] (see [Migration Guide][2]). So far, so good.

The other internal API classes currently imported (those in `com.sun.source.tree`, `com.sun.tools.javac.util`, `com.sun.tools.javadoc`) are used only to set up the compiler in the fn `parse-java`. This fn exists *only* because the default Javadoc compiler in JDK7 required each source to be specified as a file path to a `.java` file. If the JDK9 version will accept either a jar resource path, or text content all of these imports can go away! This would be the first thing to look into.


[1]: https://docs.oracle.com/javase/9/docs/api/jdk/javadoc/doclet/package-summary.html
[2]: https://docs.oracle.com/javase/9/docs/api/jdk/javadoc/doclet/package-summary.html#migration

**Comment by jeffvalk** [comment] 2018-12-04 21:59
I had a quick go at this. I have a version of `parser.clj` that works on JDK9+ without referencing any internal classes. I'll clean it up when I have time (hopefully over the weekend).

**Comment by bbatsov** [comment] 2018-12-04 23:19
@jeffvalk Fantastic news!

**Comment by jmingtan** [comment] 2018-12-05 00:42
Thanks @jeffvalk! I had a go at implementing your suggestion too but I couldn’t figure out how to make the JavadocTool accept a zip file path, looking forward to seeing your implementation :)

**Comment by jeffvalk** [comment] 2018-12-10 16:32
Update on this: The revised parser works fine with JDK9+ for all non-JDK Java sources. The sources to the JDK itself are tricky though -- partly due to the new Java module system, but mostly to a poor public API for the JDK compiler. The JDK sources are a primary use case; I'll continue to push on this to get it working.

**Comment by bbatsov** [comment] 2018-12-21 12:39
@jeffvalk How much more time do you think you'll need? I'm thinking of cutting a new cider-nrepl release over the new few days.

**Comment by jeffvalk** [comment] 2018-12-22 19:05
@bbatsov It's hard to estimate -- getting the public compiler API to work with the modular JDK sources involves a lot of digging into compiler internals to figure out why different types of access errors occur. I'm sure there's a common thread (or a few), but it's not obvious (yet) and it's certainly not well-documented.

What we could do in the meantime is release a version that works with most Java sources, but ignores the JDK sources under Java 9+. Then we can at least address the Dynapath dependency, which is what this issue was originally about.

I'll try to give this a go in the next day. If I don't manage to get it done in the next 24 hours, it will likely be another week before I can push anything useful. (Holidays and such, you know -- which, btw, happy holidays!)

**Comment by bbatsov** [comment] 2018-12-22 19:15
> What we could do in the meantime is release a version that works with most Java sources, but ignores the JDK sources under Java 9+. Then we can at least address the Dynapath dependency, which is what this issue was originally about.

I can live with this as a first step. :-)

> I'll try to give this a go in the next day. If I don't manage to get it done in the next 24 hours, it will likely be another week before I can push anything useful. (Holidays and such, you know -- which, btw, happy holidays!)

Thanks! Happy Holidays to you as well! 

As for the release - it's not that big of a deal. If we have to wait a bit for it, I guess we'll wait.

**Comment by jeffvalk** [comment] 2018-12-22 19:33
@bbatsov How far into the future do you envision Java 8 support?

**Comment by bbatsov** [comment] 2018-12-22 19:43
1-2 years more. It's reaches its official EOL in December 2020. Given the massive changes in Java 9, I assume the migration from Java 8 is going to take quite a while for some organizations.

**Comment by jeffvalk** [comment] 2018-12-22 19:54
Figured that was the case; makes sense. I'll write the 8 vs 9+ lib loading with that in mind.

Must say, if other people's experience with Java modules is like what I've had trying to get the compiler API running, Java 8 may be around for longer than anyone wants...

**Comment by bbatsov** [comment] 2018-12-22 20:06
I still haven't heard a single person say a good word about the modules. :-)

**Comment by jeffvalk** [comment] 2018-12-22 20:14
My grumbling shall not be posted here :slightly_smiling_face:

**Comment by bbatsov** [comment] 2019-03-14 20:29
@jeffvalk Any progress with this?

**Comment by jeffvalk** [comment] 2019-04-14 18:56
Apologies for the silence on my end!

#### JDK9+ Java parser
I pushed the changes that I previously mentioned in fabb9b07f4 and 33f079157e2. This updates the Java parser to work with JDK9+.

- The new parser uses only public APIs.
- The old java parser is now renamed `java.legacy-parser` and is loaded conditionally for JDK8 and below.
- Java parsing of modular sources is currently disabled. In principle, parsing these should work fine; but the compiler currently throws module access errors, and I haven't had time to look deeply at it.

#### Dynapath 
I also pushed commit 5e3bcd18bc to address the `dynapath` dependency, but did this in a separate branch as this one deserves a bit of discussion:

- dynapath 1.0 works the "right" way -- a modifiable classloader is required for runtime loading.
- When running in a REPL (via `cider-jack-in-clj`, `lein repl`, etc) , there's a `clojure.lang.DynamicClassLoader` in the hierarchy, so dynapath 1.0 works fine under both JDK8 and JDK9+. This is the actual use case.
- When running `lein test`, however, no `DynamicClassLoader` is available. This means that tests that pass when run interactively fail when run via `lein test`.

Is this the intended behavior of leiningen?

In 5e3bcd18bc, test assertions that depend on runtime-loaded resources are disabled when runtime classloading isn't available. Essentially, we have the functionality we want, it has tests that pass when run interactively...but CI (as configured) can't run the tests. Thoughts?

**Comment by bbatsov** [comment] 2019-04-15 16:59
> Is this the intended behavior of leiningen?

No idea. I guess we can discuss it with someone from their team. 

> In 5e3bcd1, test assertions that depend on runtime-loaded resources are disabled when runtime classloading isn't available. Essentially, we have the functionality we want, it has tests that pass when run interactively...but CI (as configured) can't run the tests. Thoughts?

If things work as intended we should probably move forward with this and just disable the tests for the time being.

**Comment by jeffvalk** [comment] 2019-04-16 21:54
It bothered me that tests could produce different results from a terminal vs a REPL, so I dug into it a bit. Two versions of the truth is a recipe for trouble.

The good news is that I have a possible fix for this in the dynapath 1.0 case.

The not-so-good news is that the dynapath 1.0 upgrade didn't introduce the issue; it just turned it up. It already existed under JDK9+. Case in point: to compare REPL vs terminal, you can't run `cider-test-run-project-tests` -- no namespaces are found by `orchard.namespace`.

I'll probe this a bit more.

**Comment by bbatsov** [comment] 2019-04-17 07:42
Thanks!

Btw, here's a related point https://github.com/clojure-emacs/orchard/issues/41

I think that for our simple use-case it might be a better idea to just bundle a simple ns discovery function in orchard and stop relying on c.t.n. Probably it's worth inlining whatever we're using from dynapath as well (I think that was a single function), so Orchard would eventually become self-contained and could never conflict with app dependencies.

**Comment by jeffvalk** [comment] 2019-04-17 14:15
#41 makes even more sense in light of what I mentioned above. The Tests of Many Faces all relate to classpath and namespace resolution -- exactly what the remaining dependencies are.

Much, if not all, of it traces back to https://dev.clojure.org/jira/browse/CLASSPATH-8.

**Comment by bbatsov** [comment] 2019-04-17 15:16
> It looks like the entire point of orchard.classloader and orchard.classpath is to create a fake classpath for boot projects that includes tools.jar and src.zip (here). Is this true? If so, we may be able to get rid of these namespaces (and their dependencies) altogether. We can do this via orchard.java without any faking/trickery.

Yeah, we can do this, but we are also using this fake classpath for Boot projects in CIDER (in the classpath browser). But I'd certainly love to drop the `java.classpath` dep as it's currently adding pretty much nothing (on Java 9+ it simply returns the system classpath). 

 > Can we ensure that src.zip (for all JDKs) and tools.jar (for JDK8) are available on the CI server? It would make testing more robust. Currently, we just skip testing if things aren't available, which isn't ideal.

I think that shouldn't be hard. Let's ask our resident CI expert @shen-tian about this.

**Comment by bbatsov** [comment] 2019-04-17 15:17
> #41 makes even more sense in light of what I mentioned above. The Tests of Many Faces all relate to classpath and namespace resolution -- exactly what the remaining dependencies are.

There's also #40 ;-) I'm really frustrated with deps coming from Clojure Contrib, as they are all pretty much abandonware at this point.

**Comment by jeffvalk** [comment] 2019-04-17 15:52
> I'm really frustrated with deps coming from Clojure Contrib, as they are all pretty much abandonware at this point.

And it's hard to tell what is and what isn't. The [dev.clojure.org](https://dev.clojure.org) issue tracker itself practically looks like abandonware. (I suspect a 2011 version of JIRA may be missing a security patch or two.) Alas, that's a separate topic.

**Comment by jeffvalk** [comment] 2019-04-17 17:43
@bbatsov The code that's failing the linter is code I pushed. Is there a reason the linter expects  indentation different from what `clojure-mode` produces?

**Comment by shen-tian** [comment] 2019-04-17 18:31
> 2\. Can we ensure that `src.zip` (for all JDKs) and `tools.jar` (for JDK8) are available on the CI server? It would make testing more robust. Currently, we just skip testing if things aren't available, which isn't ideal.

CI uses Docker images are derived from official OpenJDK images, so should be as standard as they come. I don't know enough about JDK to know for sure. How would one check?

There is [talk](https://github.com/Quantisan/docker-clojure/issues/62) of changing stuff further upstream, so rather don't rely on any particular details of the Docker images though.

We can probably turn tests on/off depending on Java versions, so I think rather make strong assumptions for testing (we expect `src.zip` and `tools.jar` for JDK8) and make sure those are there, rather than having the tests skipped.

**Comment by shen-tian** [comment] 2019-04-17 18:35
> @bbatsov The code that's failing the linter is code I pushed. Is there a reason the linter expects indentation different from what `clojure-mode` produces?

There's some overrides here:

https://github.com/clojure-emacs/orchard/blob/04812442739656def33c161c4f59a17c617e2a94/project.clj#L62-L66

if you just want CI to pass, just run this.

```
lein with-profile +1.10,+cljfmt cljfmt fix
```

**Comment by jeffvalk** [comment] 2019-04-18 02:04
I rewrote the classpath/classloader logic. The hacks are gone, and so is the `java.classpath` dependency.

Tests now behave the same way when run interactively and via `lein test`. And this is easier to confirm since `cider-test-run-project-tests` works again.

I'd like to push the changes with all tests run all the time.

**Comment by bbatsov** [comment] 2019-04-18 06:22
> @bbatsov The code that's failing the linter is code I pushed. Is there a reason the linter expects indentation different from what clojure-mode produces?

See https://github.com/weavejester/cljfmt/issues/46 We should probably teach `cljfmt` about this in `project.clj`, as it doesn't seem to me it indents things correctly.

> I'd like to push the changes with all tests run all the time.

👍

**Comment by bbatsov** [comment] 2019-04-18 07:14
Btw, I've fixed the indentation for `proxy` - looking at clojure-mode it didn't indent properly in this case either, so I just tweaked a bit the code in a way where clojure-mode and cljfmt would agree about it.

**Comment by shen-tian** [comment] 2019-04-18 07:31
I've had a check for `tools.jar` and `src.zip` btw. With our current CI images, we have the former for Java 8, and the later for neither 8 nor 11. Should be able to install them though. I'm adding this onto my wishlist for better CI images..

**Comment by jeffvalk** [comment] 2019-04-18 17:21
> See weavejester/cljfmt#46 We should probably teach cljfmt about this in project.clj, as it doesn't seem to me it indents things correctly.

FWIW I prefer clojure-mode's indentation over cljfmt.

**Comment by jeffvalk** [comment] 2019-04-18 17:25
> I've had a check for tools.jar and src.zip btw. With our current CI images, we have the former for Java 8, and the later for neither 8 nor 11. Should be able to install them though. I'm adding this onto my wishlist for better CI images.

For the moment, that means some tests will have to be disabled.

@shen-tian Is the wishlist a short-term or long-term one? :slightly_smiling_face: If the latter, is there another image available that includes it?

**Closed** 2019-04-18 17:37 UTC

**Comment by jeffvalk** [comment] 2019-04-18 17:56
How do you rerun a CI job?

All tests pass locally, but multiple (though not all) jobs failed on the CI server with what looks like resource loading issues.

**Comment by bbatsov** [comment] 2019-04-18 18:58
@jeffvalk When you click on a failed build there should be a button to re-run it.

**Comment by jeffvalk** [comment] 2019-04-18 19:06
If there is one, it's not obvious where...

**Comment by jeffvalk** [comment] 2019-04-18 19:11
Does it require a separate login to circleci?

**Comment by bbatsov** [comment] 2019-04-18 19:42
That's what I see

![image](https://user-images.githubusercontent.com/103882/56386734-48712080-622b-11e9-8c8f-8e5ce9df2e6c.png)

I'm always logged in there with my GH account, though.

**Comment by jeffvalk** [comment] 2019-04-18 19:43
I can reproduce the JDK8 errors by ensuring `tools.jar` exists, but does not contain the expected class files. Perhaps a bad symlink in the CI image?

**Comment by bbatsov** [comment] 2019-04-18 19:47
> Remove "fake" classpath references. It's either on the classpath or it isn't.

Btw, won't this break the lookup of resources in Boot? I think the resources were on the fake classpath, but I don't use Boot, so I don't quite remember what were they doing exactly.

**Comment by bbatsov** [comment] 2019-04-18 19:48
> Perhaps a bad symlink in the CI image?

Could be. I haven't checked the image myself - I just assumed Circle know what they are doing. :-)

**Comment by jeffvalk** [comment] 2019-04-18 19:52
> Could be. I haven't checked the image myself - I just assumed Circle know what they are doing. :-)

I'm hopeful. :-) Is there any way to check? Having `tools.jar` exist but be a bad file of some sort (content, permissions) reproduces the errors exactly, and it's the only way I've found. The tests all pass for me, and I ran all the configurations repeatedly in a loop (wanted to check for Heisenbugs).

**Comment by jeffvalk** [comment] 2019-04-18 19:56
> Btw, won't this break the lookup of resources in Boot?

The Boot logic seemed only to be appending `tools.jar` and `src.zip` onto the "fake" classpath. Since those are on the actual classpath whenever they're present, I don't see why anything fake is sensible. This said, I also don't use Boot.

**Comment by jeffvalk** [comment] 2019-04-18 19:59
BTW I don't have the dropdown menu you showed above in CircleCI. I presume it requires being logged in.

**Comment by bbatsov** [comment] 2019-04-19 11:15
I guess so. Btw, I see that on Java 11 there's some different problem:

```
lein test :only orchard.eldoc-test/test-eldoc

ERROR in (test-eldoc) (HashMap.java:1134)
arglist extraction
expected: (:eldoc (eldoc/eldoc (info/info (quote clojure.core) (quote .toString))))
  actual: java.util.ConcurrentModificationException: null
 at java.util.HashMap.computeIfAbsent (HashMap.java:1134)
    com.sun.tools.javac.model.JavacElements.unboundNameToSymbol (JavacElements.java:199)
    com.sun.tools.javac.model.JavacElements.doGetElement (JavacElements.java:182)
    com.sun.tools.javac.model.JavacElements.doGetTypeElement (JavacElements.java:172)
    com.sun.tools.javac.model.JavacElements.getTypeElement (JavacElements.java:160)
    com.sun.tools.javac.model.JavacElements.getTypeElement (JavacElements.java:87)
    orchard.java.parser$typesym.invokeStatic (parser.clj:180)
```

Doesn't happen all the time, but it's probably something worth looking into.

**Comment by jeffvalk** [comment] 2019-04-19 13:52
Yeah, this is the Heisenbug I was referring to. Happened for me on 18 of 1113 (1.6%) test runs. Not sure why it's more frequent on the CI server, but that's useful!

This one appears to be a JDK bug in the Language Model API. `ConcurrentModificationException`s are thrown whenever an iterator's collection is modified by something other than the iterator. The parser code triggering this doesn't modify anything; it only reads the tree once it's fully parsed. From the stacktrace, it seems read calls are mutating the hash map. Sneaky mutability is ugly.

I'll find a workaround.

**Comment by jeffvalk** [comment] 2019-04-22 19:50
Workaround applied.

The remaining CI build problems are related to this:

> I can reproduce the JDK8 errors by ensuring tools.jar exists, but does not contain the expected class files. Perhaps a bad symlink in the CI image?

**Comment by shen-tian** [comment] 2019-04-23 14:32
> @shen-tian Is the wishlist a short-term or long-term one? 🙂 If the latter, is there another image available that includes it?

More likely a longer term thing... I'm sure better images exist, but nothing that's explicitly maintained. 

In the short term, we can probably just install `src.zip` using `apt-get install openjdk-8-source` etc. But gonna take some experimenting to get working.

**Comment by jeffvalk** [comment] 2019-04-23 15:58
> In the short term, we can probably just install src.zip using apt-get install openjdk-8-source etc. But gonna take some experimenting to get working.

This would be good.

One quick note, if the images are Debian-based as your note suggests: The Debian packages install the JDK sources in a directory that's not a child of the JDK directory (e.g. `/usr/lib/jvm/openjdk-11/lib/src.zip` vs `/usr/lib/jvm/java-11-openjdk-amd64/`). They'll need to be symlinked manually.

**Comment by birdspider** [comment] 2019-04-24 11:24
> The Debian packages install the JDK sources in a directory that's not a child of the JDK directory 

FYI, I don't think this is debian specific but due to different java packaging guidelines? It seems (in linux world) java-8 is the last version with src.zip as child of JDK directory, otherwise within .lib/ 

    # ubuntu-bionic-18.04
    # ubuntu-cosmic-18.10
    /usr/lib/jvm/openjdk-8/src.zip

    # archlinux
    /usr/lib/jvm/java-12-adoptopenjdk/lib/src.zip
    /usr/lib/jvm/java-11-openjdk/lib/src.zip

    # ubuntu-bionic-18.04
    # ubuntu-cosmic-18.10
    # ubuntu-disco-19.04
    /usr/lib/jvm/openjdk-11/lib/src.zip

    # ubuntu-disco-19.04
    /usr/lib/jvm/openjdk-12/lib/src.zip

**Comment by jeffvalk** [comment] 2019-04-24 13:25
> I don't think this is debian specific but due to different java packaging guidelines?

I have no insight here. If there's a specific guideline, I'd be interested in knowing what it is!

> java-8 is the last version with src.zip as child of JDK directory, otherwise within ./lib/

Orchard will find `src.zip` in either of the two common locations -- in the root of the JDK or in `lib`. But the Debian/Ubuntu packages (and possibly other distros) install sources in a sibling directory to the JDK, hence the need to manually symlink `src.zip`:

```
/usr/lib/jvm/java-11-openjdk-amd64/   # openjdk-11-jdk
/usr/lib/jvm/openjdk-11/              # openjdk-11-source
```

**Comment by jeffvalk** [comment] 2019-04-24 13:42
Created #50 to track the CI configuration issue.

**Comment by jeffvalk** [comment] 2019-05-05 12:44
@bbatsov A quick note as you're thinking about getting rid of the `dynapath` dependency:

That code is easily replaced; `dynapath` itself is only a few lines. The value isn't the code, though; it's the protocol and compatibility with anything else that implements it. (This also has implications for rewriting/inlining the dependency.) Currently, any container, application server, etc that implements `dynapath`'s protocol should "just work" with Orchard's runtime classloading. If Orchard doesn't reference that protocol, this wouldn't be true.

Orchard doesn't do a lot of classloading (only `tools.jar` and `src.zip`), and I don't know how many users are running Clojure in runtime container of some sort. Maybe this isn't a use case worth supporting. Thought it was worth mentioning though.

**Comment by bbatsov** [comment] 2019-05-05 15:07
> That code is easily replaced; dynapath itself is only a few lines. The value isn't the code, though; it's the protocol and compatibility with anything else that implements it. (This also has implications for rewriting/inlining the dependency.) Currently, any container, application server, etc that implements dynapath's protocol should "just work" with Orchard's runtime classloading. If Orchard doesn't reference that protocol, this might not be true. (The actual impact depends on the container behavior.)

I wasn't aware there was any protocol to go with dynapath - for some reason I thought it was just a mechanism for dynamically loading code. 

> Orchard doesn't do a lot of classloading (only tools.jar and src.zip), and I don't know how many users are running Clojure in runtime container of some sort. Maybe this isn't a use case worth supporting. Thought it was worth mentioning though.

In general I was thinking that maybe loading some extra resources should be done by the clients, not by Orchard itself (e.g. `cider-nrepl`). `dynapath` is a relatively low-risk dependency (as it's unlikely that user code would depend on it), but still I'd be happy if we manage to get to the dream state of 0 runtime deps.

**Comment by jeffvalk** [comment] 2019-05-05 15:31
> In general I was thinking that maybe loading some extra resources should be done by the clients, not by Orchard itself ... I'd be happy if we manage to get to the dream state of 0 runtime deps.

Moving runtime classloading to the clients is definitely possible. Orchard could just check the classpath to see if specific resources are present and act accordingly.

**Comment by bbatsov** [comment] 2019-05-05 15:40
Yep, exactly.

**Comment by jumarko** [comment] 2020-08-12 03:57
This was linked from https://github.com/clojure-emacs/cider/issues/2269 but it's unclear to me whether that issue is fixed or not. Is the javadoc & source code navigation supposed to work for JDK version > 8?
