### ISSUE TITLE
Ability to expand macros which use `&env`

### ISSUE THREAD

**Issue by darkleaf** [clojure-emacs/orchard#77] opened 2019-11-06 18:00 UTC
Hi!
Is any plans to use [ztellman/riddley](https://github.com/ztellman/riddley) for macro expansion and debugging?
 
Related to
* https://github.com/clojure-emacs/cider/issues/1775
* https://github.com/clojure-emacs/cider-nrepl/issues/372

**Comment by bbatsov** [comment] 2019-12-24 16:27
Hey there!

There are no plans to use it (I'm not familiar with the library). In general 3rd party libraries can be integrated only at the middleware level, as Orchard is supposed to be self-contained by design.

**Comment by darkleaf** [comment] 2019-12-24 18:16
Cider can't debug and expand macros which uses `&env` argument. Riddley can expand such macros correctly.

**Comment by bbatsov** [comment] 2019-12-31 18:02
Understood. I'll take a closer look at the issue when I can, but everyone's more than welcome to beat me to it. I see `riddley` is a small library, so we can either emulate its approach in Orchard or leverage it directly in `cider-nrepl`.

**Comment by Cartmanishere** [comment] 2020-03-03 21:57
I think there are challenges in directly using `ridley.walk/macroexpand-all` instead of `orchard.meta/macroexpand-all`.

In the library's `macroexpand` function, even inline function call are checked for macroexpansion. 
E.g
```
(ridley.walk/macroexpand-all '(+ 1 2)
=> (. clojure.lang.Numbers (add 1 2))

(orchard.meta/macroexpand-all '(+ 1 2)
=> (+ 1 2)
```
This change in behavior will break some things down the line in debugging. 

One other problem is that orchard's macroexpand attaches the `original-form` in the metadata. Technically there is a way to be figured out to do the same thing using the `predicate` and `handler` provided by `ridley.walk/macroexpand-all`. But again, there is potential for breaking the further debugging code.

Related:
https://github.com/clojure-emacs/cider/issues/1775
https://github.com/clojure-emacs/cider-nrepl/pull/373

**Comment by vemv** [comment] 2022-01-16 05:09
In face of the caveats that @Cartmanishere mentions, and observing that riddley hasn't been maintained for a while and that https://github.com/clojure-emacs/cider/issues/1775 is closed, we can close this one as well.

Of course, a motivated hacker can pick up the task but it doesn't look like we gain much by tracking it today.

**Closed by vemv** 2022-01-16 05:09 UTC
